project_id = "nbyrcboutdtzwslfhthe"

[functions.sync-dre]
verify_jwt = false

[functions.sync-eurlex]
verify_jwt = false

[functions.import-legislation]
verify_jwt = false

[functions.generate-compliance-report]
verify_jwt = false

[functions.import-pdf-legislation]
verify_jwt = false

[functions.import-excel-legislation]
verify_jwt = false

[functions.import-dre-links]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.fix-legislation-metadata]
verify_jwt = false
